objects/Account.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>NULLVALUE(First_Name__c,&apos;&apos;)&amp;&apos; &apos;&amp;Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Loy_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loy Program</label>
        <referenceTo>CVL__Loy_Program__c</referenceTo>
        <relationshipLabel>Outlets</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Name__c</fullName>
        <formula>Promo_Campaign__r.Brand__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Coupons_Issued__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Coupons Issued</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaign Membership</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promo_Campaign__c</fullName>
        <label>Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Register_Loyalty_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-Register Loyalty Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Availability_DateTime__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Availability DateTime</label>
        <referenceTo>BusinessHours</referenceTo>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Brand</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Coupon</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Outlet__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Outlet</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Outlet</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaigns (Default Outlet)</relationshipLabel>
        <relationshipName>Promo_Campaigns1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Fixed Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Loy_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loyalty Program</label>
        <referenceTo>CVL__Loy_Program__c</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Minimum_Purchase_Amount__c</fullName>
        <label>Minimum Purchase Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Coupons_per_Member__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number of Coupons per Member</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promo_message__c</fullName>
        <label>Promo message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reedem_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reedem Points Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reedem_Rate__c</fullName>
        <label>Reedem Points Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions__c</fullName>
        <label>Terms And Conditions</label>
        <length>5000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Terms_and_conditions2__c</fullName>
        <label>Terms and conditions</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Promo Campaign</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Voucher</fullName>
        <active>true</active>
        <label>Voucher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DM001_Voucher.cls
public class DM001_Voucher {
    public static Member__c getRecord(id voucherId)
    {
        list<Member__c> lMem = 
            [
                select id,
                Name,
                Customer__c,
                Customer__r.name,
                Promo_Campaign__c,
                Coupons_Issued__c,                   
                promo_campaign__r.id,
                promo_campaign__r.Number_of_Coupons_per_Member__c,
                promo_campaign__r.RecordType.Name,
                promo_campaign__r.Coupon__c ,
                promo_campaign__r.Coupon__r.name ,  
                promo_campaign__r.Image__c ,
                Promo_Campaign__r.Expiry_Date__c,
                Promo_Campaign__r.Availability_DateTime__c,
                Promo_Campaign__r.Availability_DateTime__r.Name, 
                Promo_Campaign__r.Loy_Program__c,
                Promo_Campaign__r.Minimum_Purchase_Amount__c, 
                Promo_Campaign__r.Auto_Register_Loyalty_Member__c,
                Promo_Campaign__r.Promo_message__c,
                Promo_Campaign__r.Discount__c, 
                Promo_Campaign__r.Discount_Amount__c,                     
                Promo_Campaign__r.Reedem_Amount__c,
                Promo_Campaign__r.Reedem_Rate__c,
                Promo_Campaign__r.Brand__r.Name,
                Promo_Campaign__r.Name, 
                Promo_Campaign__r.Default_Outlet__c,
                Customer__r.Full_Name__c,
                Brand_Name__c
                from Member__c 
                where id = :voucherId
            ];
        if(lMem.isEmpty())
        {
            throw new MyException('Can\'t find voucher with \''+voucherId+'\' id.');
        }
        return lMem[0];
    }
    
    
    public static list<CVL__Loy_Transaction__c> getTxn(id voucherId)
    {
        return 
            [
                select 
                id,
                Name,
                Currency_Code__c,
                Parent_Transaction__c,
                CVL__Type__c, 
                CVL__Points__c, 
                CVL__Accrued_Points_1__c, 
                CVL__Accrued_Points_2__c,
                Base_Amount__c,
                Net_Amount__c,
                Discount__c,
                CVL__Member__c ,
                voucher_code2__c
                from CVL__Loy_Transaction__c 
                where voucher__c = :voucherId 
            ];
    }
    public static Member__c getTerms(id voucherId)
    {
        
        list<Member__c> lMem = 
            [
                select id,
                Name,
                Customer__c,
                Customer__r.name,
                Promo_Campaign__c,
                Coupons_Issued__c,                   
                Promo_Campaign__r.Brand__r.Name,
                Promo_Campaign__r.Name,                                
                Customer__r.Full_Name__c,
                Brand_Name__c,
                promo_campaign__r.Image__c , 
                Promo_Campaign__r.Promo_message__c,               
                Promo_Campaign__r.Terms_and_conditions2__c 
                from Member__c 
                where id = :voucherId
            ];
        if(lMem.isEmpty())
        {
            throw new MyException('Can\'t find voucher with \''+voucherId+'\' id.');
        }
        return lMem[0];
    }
    
    public static promo_campaign__c getTerms2(id campId)
    {
        list<promo_campaign__c> lMem = 
            [
                select id,
				name,
               	Image__c , 
                Promo_message__c,               
                Terms_and_conditions2__c,
                Terms_and_conditions__c               
                from promo_campaign__c 
                where id = :campId
            ];
        if(lMem.isEmpty())
        {
            throw new MyException('Can\'t find campaign with \''+campId+'\' id.');
        }
        return lMem[0];
    }   
}