objects/Account.object
<CustomObject>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>NULLVALUE(First_Name__c,&apos;&apos;)&amp;&apos; &apos;&amp;Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaign Membership</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promo_Campaign__c</fullName>
        <label>Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Promo_message__c</fullName>
        <label>Promo message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promo Campaign</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VFC002_ReedemVoucher.cls
public class VFC002_ReedemVoucher 
{
    public string sMemberId{get;set;}
    public string imageURL {get;set;}
	
    public member__c mem{get;set;}
    public string sMemberName {get;set;}
    public string sCampaignName {get;set;}
    public string sPromoMessage {get;set;}
    public decimal dVal {get;set;}
    public string sPIN {get;set;}
    public boolean bRender {get;set;}
      
    public VFC002_ReedemVoucher() 
    { 
        bRender = true;
        try
        {
            sMemberId = ApexPages.currentPage().getParameters().get('memberId');
            if(sMemberId == null)
                sMemberId = 'a011r00003d7IWa';
            mem = DM001_Voucher.getRecord(sMemberId);  
            imageURL = mem.Promo_Campaign__r.Image__c;
            sCampaignName = mem.Promo_Campaign__r.Name;  
            sMemberName = mem.Customer__r.Full_Name__c;
            sPromoMessage = mem.Promo_Campaign__r.Promo_message__c;
            SM012_Voucher.validate(mem);
        }catch(Exception e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
            bRender = false;             
        }
    }
    public PageReference doReedem()
    {
        id loyMemId =null;
        try
        {
			loyMemId = SM012_Voucher.doReedem2(mem.id, dVal, sPIN,true,1);
        }catch(Exception e)
        {
            ApexPages.addMessage (new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
            bRender = false;             
        }
        if(loyMemId != null)
			return new PageReference('/apex/'+SM011_Const.vfpMemberinfo+'?memberId='+loyMemId); 
        else
            return null;
    }
}