objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Loy_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loy Program</label>
        <referenceTo>CVL__Loy_Program__c</referenceTo>
        <relationshipLabel>Outlets</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality</label>
        <picklist>
            <picklistValues>
                <fullName>Arabian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIN__c</fullName>
        <label>PIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Image__c</fullName>
        <formula>Promo_Campaign__r.Image__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <formula>Promo_Campaign__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Promo_Message__c</fullName>
        <formula>IF(Promo_Campaign__r.Message__c &lt;&gt; &apos;&apos;,Promo_Campaign__r.Message__c, Promo_Campaign__r.Promo_message__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Promo Message</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaign Membership</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promo_Campaign__c</fullName>
        <label>Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reedem_URL__c</fullName>
        <formula>&apos;https://viafone.secure.force.com/apex/VFP003_ReedemVoucher3?memberId=&apos; &amp; Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reedem URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Category_Flag2__c</fullName>
        <formula>RecordType.Name = &apos;Category&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category Flag2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Loy_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loyalty Program</label>
        <referenceTo>CVL__Loy_Program__c</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <formula>IF(
Discount_Calc__c &lt;&gt;&apos;&apos;, 
	$Label.Get &amp; 
	&apos; &apos; &amp; 
	Discount_Calc__c &amp; 
	&apos; &apos;&amp; 
	$Label.of_discount &amp;
	IF(Reedem_Amount__c&gt;0,
		&apos; &apos;&amp; 
		$Label.for &amp;
		&apos; &apos; &amp; 
		TEXT(Reedem_Amount__c) &amp;
		&apos; &apos;&amp; 
		Reedem_Unit_of_Measure__c
	,&apos;&apos;)
,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Message</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promo_message__c</fullName>
        <label>Promo message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reedem_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reedem Points Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promo Campaign</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SM009_Register.cls
@RestResource(urlMapping='/member/*')
global class SM009_Register 
{
    global class RegisterResponse
    {
        public string ErrorCode {get;set;}
        public string ErrorMessage {get;set;} 
        public string RecordId {get;set;}
        public string SessionId {get;set;}
        
        public RegisterResponse()
        {
            ErrorCode = '';
            ErrorMessage = '';
            RecordId = '';
            SessionId = '';
        }
    }
    
    global class MemberResponse
    {
        public string ErrorCode {get;set;}
        public string ErrorMessage {get;set;} 
		public CVL__Loy_Program__c program {get;set;}
		public CVL__Loy_Member__c member {get;set;}  
        public list<Member__c > vouchers {get;set;}
		public list<Promo_Campaign__c> vouchers2 {get;set;}      
        public MemberResponse()
        {
            ErrorCode = '';
            ErrorMessage = '';
            
        }
    }
    
    @HttpGet
    global static MemberResponse doGet()
    {
        MemberResponse resp = new MemberResponse();
        try
        { 
            string memId = (string)RestContext.request.params.get('id');    
            
            resp.member = DM003_LoyMember.getRecord(memId);
            list<CVL__Loy_Program__c> lpr = [select id, name, logo__c,title__c,promo_Message__c from CVL__Loy_Program__c where id = :resp.member.CVL__Program__c];
            if(lpr.isEmpty())
            {
                throw new MyException('Can not find loy program '+resp.member.CVL__Program__c);
            }
            resp.program =lpr[0];
            
            
            resp.vouchers = [select id,campaign_name__c,campaign_promo_message__c, campaign_image__c,reedem_url__c from member__c where Customer__c = :resp.member.CVL__Account__c and Promo_Campaign__r.Loy_Program__c  = :resp.program.id   and Status__c <> 'Used'];
        }catch(Exception e)
        {
            resp.ErrorCode = '1';
            resp.ErrorMessage = ''+e.getMessage()+' '+e.getStackTraceString()+' '+e.getLineNumber();   
            if(Test.isRunningTest())
                throw e;
        }
        resp.vouchers2 = 
            [ select id,
                Promo_message__c,
                Image__c,
                Name,
                message__c ,
                Reedem_Amount__c
                from promo_campaign__c 
                where 
                Loy_Program__c  = :resp.member.CVL__Program__c
                and (Expiry_Date__c = null OR Expiry_Date__c > TODAY)
             and Category_flag2__c <> true
            ];
        return resp;
    }
    
       @HttpPost
	global static RegisterResponse doPost()
    {
        RegisterResponse ret = new RegisterResponse();
        try
        {
            string sPhone = (string)RestContext.request.params.get('phone');
            string sFirstName = (string)RestContext.request.params.get('firstName');        
            string sLastName = (string)RestContext.request.params.get('lastname');
            string sGender =  (string)RestContext.request.params.get('gender');
            string sNationality =  (string)RestContext.request.params.get('nationality'); 
            string sProgramId = (string)RestContext.request.params.get('program'); 
            string sBirthdate = (string)RestContext.request.params.get('birthdate'); 
            string sPIN  = (string)RestContext.request.params.get('pin');
            ret.recordId =  register(sProgramId, sNationality, sGender,  sLastName, sFirstName, sPhone,'',sPIN);           
        }catch(Exception e)
        {
            ret.ErrorCode = '1';
            ret.ErrorMessage = ''+e.getMessage()+' '+e.getStackTraceString()+' '+e.getLineNumber();
            if(Test.isRunningTest())
                throw e;
        }
        return ret;

    }
    
    
    public static string register(string sProgramId, string sNationality, string sGender, string sLastName,string sFirstName,string sPhone,string sEmail,string sPIN)
    {
    	return register0(sProgramId, sNationality, sGender, sLastName, sFirstName, sPhone, sEmail, sPIN).id;
    }
    
    public static CVL__Loy_Member__c register0(string sProgramId, string sNationality, string sGender, string sLastName,string sFirstName,string sPhone,string sEmail,string sPIN)
    {
                 if(sProgramId == null)
        {
            sProgramId = SM010_Utils.getValue('Default_Program_Id');
        }
        id typeId = null;
        list<recordtype> lType = [select id from recordtype where sobjecttype = 'Account' and name = 'Customer'];
        if(!lType.isEmpty())
            typeId = lType[0].id;
       	list<account> lAcc = [select id from account where phone = :sPhone and RecordTypeId = :typeId];

        account acc = null;
        if(!lAcc.isEmpty())
        {
            acc = lAcc[0];
        }
        else
        {
            acc = new account();
            acc.name = slastname;
            acc.First_Name__c = sFirstName;
            acc.Phone = sPhone;
            if(typeId != null)
            	acc.RecordTypeId = typeId;
            acc.Nationality__c = sNationality;
            acc.Description = '';
            acc.Gender__c = sGender;
            
            insert acc;           
        }
        CVL__Loy_Member__c mem = null;
        list<CVL__Loy_Member__c> lMem = [select id,CVL__Account__c,WhatsAppContext__c from CVL__Loy_Member__c where CVL__Account__c = :acc.id and CVL__Program__c = :sProgramId];
        if(!lMem.isEmpty())
        {
            mem = lMem[0];
        }
        else
        {
            mem = new CVL__Loy_Member__c();
            mem.CVL__Program__c = sProgramId;
            mem.CVL__Account__c  = acc.id;
            mem.CVL__Joined_Date__c = date.today();
            mem.PIN__c = sPIN;
            mem.WhatsAppContext__c  = 'getName';
            insert mem;    
        }
        
        SM006_CheckSms.sendSms(mem.Id);            
		return mem;  
    }



}