objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Category1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loy_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loy Program</label>
        <referenceTo>CVL__Loy_Program__c</referenceTo>
        <relationshipLabel>Outlets</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIN__c</fullName>
        <label>PIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Brand</fullName>
        <active>true</active>
        <label>Brand</label>
    </recordTypes>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <recordTypes>
        <fullName>Outlet</fullName>
        <active>true</active>
        <label>Outlet</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign_Outlet__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Brand or Outlet</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Brand_or_Outlet_Flag__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Campaign_Outlets</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promo_Campaign__c</fullName>
        <label>Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Eligible Outlets</relationshipLabel>
        <relationshipName>Campaign_Outlets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Campaign Outlet</label>
    <nameField>
        <displayFormat>CA{00000000}</displayFormat>
        <label>Campaign Outlet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Outlets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Flow__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Flow</label>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaign Membership</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promo_Campaign__c</fullName>
        <label>Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Register_Loyalty_Member__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto-Register Loyalty Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Discount_Amount__c</fullName>
        <label>Discount Fixed Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loy_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loyalty Program</label>
        <referenceTo>CVL__Loy_Program__c</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Promo_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Child_Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reedem_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reedem Points Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reedem_Rate__c</fullName>
        <label>Reedem Points Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Coupon_Inventory__c</fullName>
        <label>Total Coupon Inventory</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promo Campaign</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Promo_Rel__c.object
<CustomObject>
    <fields>
        <fullName>Next_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Next Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Previous Campaigns</relationshipLabel>
        <relationshipName>Prev_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prev_Campaign__c</fullName>
        <label>Prev Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Cross Promotions</relationshipLabel>
        <relationshipName>Next_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Promo Relationship</label>
    <nameField>
        <displayFormat>PR{000000000}</displayFormat>
        <label>Promo Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SM001_DataFactory.cls
public class SM001_DataFactory 
{
    public recordtype custType;
    public recordtype brandType;
    public recordtype outletType;    
    public account brand;
    public account outlet;    
    public account cust;
    public account cust2;
    public Promo_Campaign__c  camp;
    public Promo_Campaign__c  camp2;    
    public Member__c mem;
    public Member__c mem2;    
    public Campaign_Outlet__c campout;
    public CVL__Loy_Program__c prog;
    public CVL__Loy_Program__c prog2;    
    public CVL__Loy_Tier__c tier;
    public CVL__Loy_Member__c lmem;
    public SM001_DataFactory()
    {
        Initialize();
    }
    public void Initialize()
    {
        custType = [select id,name, sobjecttype from recordtype where sobjecttype = 'Account' and name = 'Customer'];
        brandType = [select id,name, sobjecttype from recordtype where sobjecttype = 'Account' and name = 'Brand'];  
        outletType = [select id,name, sobjecttype from recordtype where sobjecttype = 'Account' and name = 'Outlet'];
        brand = new account(name= 'brand1',recordtypeid = brandType.id,PIN__c ='111');
        insert brand;
        cust = new account(name = 'cust1',recordtypeid = custType.id,phone = '12345');
        insert cust;
 
        cust2 = new account(name = 'cust2',recordtypeid = custType.id,phone = '23456');
        insert cust2;
        
        prog = new CVL__Loy_Program__c ();
        prog.Name = 'prog123';
        insert prog;
        
        tier = new CVL__Loy_Tier__c();
        tier.CVL__Upper_Limit_Of_The_Range__c=10000;
        tier.CVL__Lower_End_Of_The_Range__c=0;
        tier.CVL__Program__c=prog.id;
        tier.CVL__Discount__c=0;
        
        insert tier;
        prog.Loy_Tier__c = tier.id;
        update prog;
        outlet = new account(name=  'outlet1', recordtypeid = outletType.id,PIN__c ='1111');
        outlet.Loy_Program__c = prog.id;
        insert outlet;
        
        Category__c cat = new Category__c ();
        cat.Category__c = 'Category1';
        cat.Account__c = outlet.id;
        insert cat;
        
        prog2 = new CVL__Loy_Program__c ();
        prog2.Name = 'prog234';
        insert prog2;
			        
        camp = new Promo_Campaign__c ();
        camp.name = 'voucher1';
        camp.Auto_Register_Loyalty_Member__c = true;
        camp.Loy_Program__c = prog.id;
        camp.Discount__c = 1;
        camp.Discount_Amount__c = 1;        
        camp.Reedem_Amount__c =10;
        camp.Reedem_Rate__c = 0.01;
        camp.Total_Coupon_Inventory__c = 10;
        insert camp;
        
        camp2 = new Promo_Campaign__c ();
        camp2.name = 'voucher2';
        camp2.Auto_Register_Loyalty_Member__c = true;
        camp2.Loy_Program__c = prog.id;
        camp2.Total_Coupon_Inventory__c = 10;
        camp2.Parent_Promo_Campaign__c = camp.Id;
        insert camp2;
        
        Promo_Rel__c rel = new Promo_Rel__c();
        rel.Prev_Campaign__c = camp.id;
        rel.Next_Campaign__c = camp2.id;
        insert rel;
        
        list<Member__c> mems = new list<Member__c>();
        for(integer i =0;i<25; i++)
        {
            mem = new Member__c();
            mem.name = 'm'+i;
            mem.Promo_Campaign__c = camp.id;
            mem.Customer__c = cust.id;
            mems.add(mem);
        }

        mem2 = new Member__c();
        mem2.Promo_Campaign__c = camp.id;
        mem2.Customer__c = cust2.id;
        mems.add(mem2);
        
        insert mems;
        
        campout = new Campaign_Outlet__c();
        campout.Account__c = brand.id;
        campout.Promo_Campaign__c = camp.id;
        insert campout;
        
		campout = new Campaign_Outlet__c();
        campout.Account__c = brand.id;
        campout.Promo_Campaign__c = camp2.id;
        insert campout;
        
        Flow__c f = new Flow__c();
        f.Name = 'getPromotions';
        insert f;
        
   
         
        lmem = new CVL__Loy_Member__c();
        lmem.CVL__Account__c = cust.id;
        lmem.CVL__Program__c = prog.id;
        lmem.CVL__Points_2__c = 20000;
        lmem.PIN__c = '1111';
        insert lmem;
    }

}