objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Member Coupons</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Coupons_Issued__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Coupons Issued</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaign Membership</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promo_Campaign__c</fullName>
        <label>Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Coupon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Coupon</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Product2.Family</field>
                <operation>equals</operation>
                <value>Coupon</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Coupons_per_Member__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number of Coupons per Member</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Promo Campaign</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Campaigns</pluralLabel>
    <recordTypes>
        <fullName>Voucher</fullName>
        <active>true</active>
        <label>Voucher</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SM008_CouponsRest.cls
/*That class reedems voucher in Engati chatbot on HttpGet*/
@RestResource(urlMapping='/coupons/*')
global class SM008_CouponsRest 
{
    @HttpGet
    global static map<string,map<string,string>> getResponse()
    {
        string sMessage  = '';
        try
        {
            RestRequest  req = RestContext.request;
            map<string,object> mPar = req.params;
            string sMemberId = (string)mPar.get('memberId');
            member__c mem = DM001_Voucher.getRecord(sMemberId);
            if(mem.Coupons_Issued__c == null)
                mem.Coupons_Issued__c =0;
            if(mem.Coupons_Issued__c>=mem.promo_campaign__r.Number_of_Coupons_per_Member__c)
            {
                throw new MyException('You\'ve reached the limit of coupons in this campaign.');
            }
            asset a = new asset();
            a.accountid= mem.Customer__c;
            a.Product2Id = mem.promo_campaign__r.Coupon__c;
            a.Member__c = mem.id;
            a.Name =  mem.promo_campaign__r.Coupon__r.name+' '+mem.Customer__r.name;
            insert a;
            
            mem.Coupons_Issued__c +=1;
            update mem;
            system.debug('id: '+a.id);
            string couponCode = ((string) (a.id)).substring(6,15);
            system.debug('code: '+couponcode);
        }catch(Exception e)
        {
            sMessage = e.getMessage();
        }
        return getEngatiMessage(sMessage);
    }
    public static map<string,map<string,string>>  getEngatiMessage(string sMess)
    {
        map<string,map<string,string>> ret = new map<string,map<string,string>> ();
        map<string,string> rdata = new map<string,string>();
        ret.put('data', rdata);       
        rdata.put('text', sMess);
        rdata.put('type', 'text');        
        return ret;        
    }
}