objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_Image__c</fullName>
        <formula>Promo_Campaign__r.Image__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Name__c</fullName>
        <formula>Promo_Campaign__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Promo_Message__c</fullName>
        <formula>IF(Promo_Campaign__r.Message__c &lt;&gt; &apos;&apos;,Promo_Campaign__r.Message__c, Promo_Campaign__r.Promo_message__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Promo Message</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Customer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promo Campaign Membership</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Promo_Campaign__c</fullName>
        <label>Promo Campaign</label>
        <referenceTo>Promo_Campaign__c</referenceTo>
        <relationshipLabel>Members</relationshipLabel>
        <relationshipName>Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reedem_URL__c</fullName>
        <formula>&apos;https://viafone.secure.force.com/apex/VFP003_ReedemVoucher3?memberId=&apos; &amp; Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reedem URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Used</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Promo_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount %</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loy_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loyalty Program</label>
        <referenceTo>CVL__Loy_Program__c</referenceTo>
        <relationshipLabel>Promo Campaigns</relationshipLabel>
        <relationshipName>Promo_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_message__c</fullName>
        <label>Promo message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promo Campaign</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promo Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/VFC004_MemberInfo.cls
public class VFC004_MemberInfo 
{
    public string sMemId {get;set;}
    public string sPhone {get;set;}
    public CVL__Loy_Member__c mem {get;set;}
    public CVL__Loy_Program__c pr {get;set;}
    public list<Member__c > vouchers {get;set;}
    public map<id,Member__c > mvoucher ;
    public boolean bRender {get;set;}
    public integer i=0;
    public boolean bRenderPromotion {get;set;}
    public string curPromoId {get;set;}
    public  Member__c curPromo {get;set;}
    public VFC004_MemberInfo() 
    { 
        try
        {
            sMemId = SM010_Utils.getParam('memberId');
            sPhone= SM010_Utils.getParam('phone');
            if(sMemId == '')
                sMemId = 'a071r00001ERpOi';
            getMemberInfo();
            
			bRender = true;
        }catch(Exception e)
        {
            bRender = false;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage())); 
        }
    }
    
    public void getMemberInfo()
    {

        list<CVL__Loy_Member__c> lMem = null;
        
        if(sMemID != '')
            lMem = [select id, Full_Name__c,Tier_Name__c,Discount__c, CVL__Points_1__c , CVL__Points_2__c, CVL__Program__c, CVL__Account__c   from CVL__Loy_Member__c where id = :sMemId];
		else
        {
           lMem = [select id, Full_Name__c,Tier_Name__c,Discount__c, CVL__Points_1__c , CVL__Points_2__c, CVL__Program__c  from CVL__Loy_Member__c where CVL__Account__r.phone = :sphone];
        }
        if(lMem.isEmpty())
        {
            throw new MyException('Can not find member '+sMemId);
        }
        mem = lMem[0];
        
		list<CVL__Loy_Program__c> lpr = [select id, name, logo__c,title__c,promo_Message__c from CVL__Loy_Program__c where id = :mem.CVL__Program__c];
        if(lpr.isEmpty())
        {
			throw new MyException('Can not find loy program'+mem.CVL__Program__c);
        }
        pr =lpr[0];
        mvoucher = new map<id,Member__c >();      
		vouchers = [select id,campaign_name__c,campaign_promo_message__c, campaign_image__c,reedem_url__c from member__c where Customer__c = :mem.CVL__Account__c and Promo_Campaign__r.Loy_Program__c  = :pr.id   and Status__c <> 'Used'];
    	if(vouchers.isEmpty())
        {
            bRenderPromotion = false;
        }
        else
        {
            curPromo = vouchers[0];
            vouchers.remove(0);
        }
    }
}